<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Core\Entities\**" />
    <EmbeddedResource Remove="Core\Entities\**" />
    <None Remove="Core\Entities\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="SlaCalculation\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CSparse" Version="4.4.1" />
  </ItemGroup>

</Project>
